// react-doctor configuration. Schema confirmed against react-doctor@0.8.3;
// the config type is not imported because react-doctor is not a dependency.
// Exclusion policy: code fixes preferred; every entry is scoped to the exact
// file + rule pair with its justification so future diagnostics still surface.

export default {
  ignore: {
    overrides: [
      {
        // Vendored shadcn/ui (components.json — "ui": "@/components/ui"):
        // upstream-owned, regenerated by the shadcn CLI on add/upgrade, so
        // project React rules must not demand refactors of it. The carousel
        // setApi/onSelect effects are embla's required wiring.
        files: ["components/ui/carousel.tsx"],
        rules: [
          "react-doctor/no-pass-data-to-parent",
          "react-doctor/no-pass-live-state-to-parent",
          "react-doctor/no-prop-callback-in-effect",
          "react-doctor/jsx-no-constructed-context-values",
          "react-hooks-js/set-state-in-effect",
        ],
      },
      {
        // Vendored shadcn/ui: kept as part of the upstream-managed set;
        // deleting files individually breaks the managed-directory
        // convention.
        files: ["components/ui/aspect-ratio.tsx"],
        rules: ["deslop/unused-file"],
      },
      {
        // Framework convention (next-intl): createNavigation(routing)
        // returns the full locale-aware navigation API and the documented
        // pattern is to destructure and re-export all of it so consumers
        // import from one stable module. Unused members are deliberate API
        // surface, not dead code.
        files: ["shared/i18n/navigation.ts"],
        rules: ["deslop/unused-export"],
      },
      {
        // No-JS fallback: the deferred font stylesheet is preload-flipped by
        // inline script for JS clients; noscript clients need a plain link,
        // which next/head cannot express conditionally.
        files: ["app/root-document.tsx"],
        rules: ["react-doctor/nextjs-no-css-link"],
      },
      {
        // Framework-mandated pattern (next-intl): getRequestConfig must load
        // locale messages via dynamic imports with an interpolated path —
        // the locale is only known at request time, and bundlers code-split
        // the context import correctly. No plain-string alternative exists.
        files: ["shared/i18n/request.ts"],
        rules: ["react-doctor/no-dynamic-import-path"],
      },
    ],
  },
};
