import { defineConfig } from "oxfmt";
import ultracite from "ultracite/oxfmt";

export default defineConfig({
  ...ultracite,
  ignorePatterns: [
    // Generated by scripts/slice-fonts.py; machine-owned, not hand-formatted.
    "public/fonts/deferred-fonts.css",
  ],
});
